# Generated by Django 5.0 on 2024-04-12 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chestpaintype', models.CharField(choices=[('0', 'Non-Anginal Pain'), ('1', 'Typical Angina'), ('2', 'Atypical Angina'), ('3', 'Asymptomatic')], max_length=50)),
                ('restingbp', models.PositiveSmallIntegerField()),
                ('Cholesterol', models.PositiveSmallIntegerField()),
                ('fastingbs', models.CharField(choices=[('0', 'less than 120 mg/dl'), ('1', 'greater than 120 mg/dl')], max_length=100)),
                ('restingecg', models.CharField(choices=[('0', 'Normal'), ('1', 'Having'), ('2', 'Wave Abnormality')], max_length=50)),
                ('maxhr', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(202)])),
                ('exerciseangina', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=50)),
                ('oldpeak', models.PositiveIntegerField()),
                ('st_slope', models.PositiveIntegerField()),
                ('heartdisease', models.PositiveBigIntegerField(choices=[(0, 0), (1, 1)])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart_app.patients')),
            ],
        ),
    ]
