# Generated by Django 5.0 on 2024-04-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0002_medical_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical_history',
            options={'verbose_name_plural': 'Medical History'},
        ),
        migrations.AddField(
            model_name='medical_history',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
