# Generated by Django 5.0 on 2024-04-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0003_alter_medical_history_options_medical_history_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_history',
            old_name='date',
            new_name='date_recorded',
        ),
    ]
