# Generated by Django 5.0 on 2024-04-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0004_rename_date_medical_history_date_recorded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='gender',
            new_name='sex',
        ),
    ]
