# Generated by Django 5.0 on 2024-04-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0005_rename_gender_patients_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='heartdisease',
            field=models.PositiveBigIntegerField(blank=True, choices=[(0, 0), (1, 1)], null=True),
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='st_slope',
            field=models.CharField(choices=[('0', 'Down'), ('1', 'Flat'), ('2', 'Up')], max_length=20),
        ),
    ]
