# Generated by Django 5.0 on 2024-04-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0006_alter_medical_history_heartdisease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(help_text='Please use this format: <em>YYYY-MM-DD</em>'),
        ),
    ]
