# Generated by Django 5.0 on 2024-04-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0007_alter_patients_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
