# Generated by Django 5.0 on 2024-04-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0008_doctor_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medical_History',
            new_name='Heart_Medical_History',
        ),
    ]
