# Generated by Django 5.0 on 2024-04-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0009_rename_medical_history_heart_medical_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heart_medical_history',
            old_name='Cholesterol',
            new_name='cholesterol',
        ),
    ]
