# Generated by Django 5.0 on 2024-04-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0010_rename_cholesterol_heart_medical_history_cholesterol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_Test_from_Heart_dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart_app.patients')),
            ],
        ),
    ]
