# Generated by Django 5.0 on 2024-04-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0013_alter_recordsfromconsult_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
