# Generated by Django 5.0 on 2024-04-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0014_hospitaldisease'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heart_app.hospitaldisease'),
        ),
    ]
