# Generated by Django 5.0 on 2024-04-14 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0019_rename_assigned_test_from_heart_dep_assigned_test_from_doctor_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart_medical_history',
            name='maxhr',
            field=models.PositiveIntegerField(help_text='Number between 60 and 202', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(202)]),
        ),
    ]
