# Generated by Django 5.0 on 2024-04-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0020_alter_heart_medical_history_maxhr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart_medical_history',
            name='oldpeak',
            field=models.FloatField(default=0.0),
        ),
    ]
