# Generated by Django 5.0 on 2024-04-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0021_alter_heart_medical_history_oldpeak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart_medical_history',
            name='oldpeak',
            field=models.FloatField(),
        ),
    ]
