# Generated by Django 5.0 on 2024-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0022_alter_heart_medical_history_oldpeak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AddField(
            model_name='heart_medical_history',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heart_medical_history',
            name='sex',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male')], max_length=1, null=True),
        ),
    ]
