# Generated by Django 5.0 on 2024-04-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0023_rename_gender_doctor_sex_heart_medical_history_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart_medical_history',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
