# Generated by Django 5.0 on 2024-04-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0024_alter_heart_medical_history_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart_medical_history',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
