# Generated by Django 5.0 on 2024-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0027_alter_heart_medical_history_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Doctors_profile'),
        ),
    ]
